import 'package:flutter/material.dart';
import 'package:flutter_svg/flutter_svg.dart';
import 'package:alumina/shared/shared.dart' as Styles;

final Widget arrowleft = SvgPicture.asset('assets/svgs/arrow-left-icon.svg', semanticsLabel: 'arrow left', color: Styles.orangeE23C18,);
final Widget arrowight = SvgPicture.asset('assets/svgs/arrow-right-icon.svg', semanticsLabel: 'arrow right', color: Styles.orangeE23C18);
final Widget arrowightF1C3B9 = SvgPicture.asset('assets/svgs/arrow-right-icon.svg', semanticsLabel: 'arrow right', color: Styles.orangeF1C3B9);
final Widget arrowightFFFFFF = SvgPicture.asset('assets/svgs/arrow-right-icon.svg', semanticsLabel: 'arrow right', color: Colors.white);
final Widget arrowight2D415F = SvgPicture.asset('assets/svgs/arrow-right-icon.svg', semanticsLabel: 'arrow right', color: Styles.blue2D415F);
final Widget eye = SvgPicture.asset('assets/svgs/eye-icon.svg', semanticsLabel: 'eye', color: Styles.orangeE23C18);
final Widget eyeFFE9E4 = SvgPicture.asset('assets/svgs/eye-icon.svg', semanticsLabel: 'eye', color: Styles.orangeFFE9E4);
final Widget eyeoff = SvgPicture.asset('assets/svgs/eye-off-icon.svg', semanticsLabel: 'eye off', color: Styles.orangeE23C18);
final Widget eyeoffFFE9E4 = SvgPicture.asset('assets/svgs/eye-off-icon.svg', semanticsLabel: 'eye off', color: Styles.orangeFFE9E4);
final Widget facebook = SvgPicture.asset('assets/svgs/facebook-icon.svg', semanticsLabel: 'facebook', color: Styles.orangeE23C18);
final Widget facebookF1C3B9 = SvgPicture.asset('assets/svgs/facebook-icon.svg', semanticsLabel: 'facebook', color: Styles.orangeF1C3B9);
final Widget google = SvgPicture.asset('assets/svgs/google-icon.svg', semanticsLabel: 'google', color: Styles.orangeE23C18);
final Widget googleF1C3B9 = SvgPicture.asset('assets/svgs/google-icon.svg', semanticsLabel: 'google', color: Styles.orangeF1C3B9);
final Widget home = SvgPicture.asset('assets/svgs/home-icon.svg', semanticsLabel: 'home', color: Styles.orangeE23C18);
final Widget image = SvgPicture.asset('assets/svgs/image-icon.svg', semanticsLabel: 'image', color: Styles.orangeE23C18);
final Widget imageDDE9FB = SvgPicture.asset('assets/svgs/image-icon.svg', semanticsLabel: 'image', color: Styles.blueDDE9FB);
final Widget logout = SvgPicture.asset('assets/svgs/log-out-icon.svg', semanticsLabel: 'log out', color: Styles.orangeE23C18);
final Widget mail = SvgPicture.asset('assets/svgs/mail-icon.svg', semanticsLabel: 'mail', color: Styles.orangeE23C18);
final Widget mailF1C3B9 = SvgPicture.asset('assets/svgs/mail-icon.svg', semanticsLabel: 'mail', color: Styles.orangeF1C3B9);
final Widget mailFFE9E4 = SvgPicture.asset('assets/svgs/mail-icon.svg', semanticsLabel: 'mail', color: Styles.orangeFFE9E4);
final Widget mappin = SvgPicture.asset('assets/svgs/map-pin-icon.svg', semanticsLabel: 'map pin', color: Styles.orangeE23C18);
final Widget menu = SvgPicture.asset('assets/svgs/menu-icon.svg', semanticsLabel: 'menu-icon', color: Styles.orangeE23C18);
final Widget messagesquare = SvgPicture.asset('assets/svgs/message-square-icon.svg', semanticsLabel: 'message square', color: Styles.orangeE23C18);
final Widget messagecircle = SvgPicture.asset('assets/svgs/message-circle-icon.svg', semanticsLabel: 'message circle', color: Styles.orangeE23C18);
final Widget settings = SvgPicture.asset('assets/svgs/settings-icon.svg', semanticsLabel: 'settings', color: Styles.orangeE23C18);
final Widget smartphone = SvgPicture.asset('assets/svgs/smartphone-icon.svg', semanticsLabel: 'smartphone', color: Styles.orangeE23C18);
final Widget smartphoneDDE9FB = SvgPicture.asset('assets/svgs/smartphone-icon.svg', semanticsLabel: 'smartphone', color: Styles.blueDDE9FB);
final Widget user = SvgPicture.asset('assets/svgs/user-icon.svg', semanticsLabel: 'user', color: Styles.orangeE23C18);

final Widget logo = SvgPicture.asset('assets/svgs/logo.svg', semanticsLabel: 'logo');
